---
# Let's do some stuff we know we need to do for each and every machine
# but we do not want to do this for the Synology!
- name: Talk to all hosts and learn about them
  hosts: all
  tasks:
    - name: Classify Linux hosts depending on their distribution
      group_by:
        key: family_{{ ansible_facts['os_family'] }}

# Do some OS specific stuff like adding the required repositories

# Let's start with RedHat based systems
- hosts: family_RedHat
  name: RHEL-based setup
  become: yes
  gather_facts: False
  tasks:
    - name: Install Microsoft GPG key
      dnf_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present
    - name: Add Microsoft Visual Studio Code repository
      dnf_repository:
        name: vscode
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        gpgcheck: yes
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        enabled: yes
    - name: Add Microsoft Edge repository
      dnf_repository:
        name: microsoft-edge-beta
        baseurl: https://packages.microsoft.com/yumrepos/edge
        gpgcheck: yes
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        enabled: yes

# Let's do the same for Debian based systems
- hosts: family_Debian
  name: Debian-based setup
  become: yes
  gather_facts: False
    tasks:
    - name: Install Microsoft GPG key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present
    - name: Add Microsoft Visual Studio Code repository
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        state: present
    - name: Add Microsoft Edge repository
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main
        state: present

# Now finish with the installation of some required packages on any system.
- hosts: all
  name: Install packages from file
  become: yes
  tasks:
    - name: Install packages from file
      package:
        name: "{{ lookup('file', 'files/packages.txt').split('\n') }}"
        state: present