---
- name: pb_upd_packages
  hosts: all
  become: yes
  tasks:
    - name: Update caches and upgrade outdated packages on Debian based Linux OS
      when: ansible_facts['os_family'] == "Debian"
      apt:
        name: "*"
        cache_valid_time: 3600
        state: latest
    - name: Remove useless packages from the cache on Debian based Linux OS
      when: ansible_facts['os_family'] == "Debian"
      apt:
        autoclean: yes
    - name: Remove dependancies that are no longer needed on Debian based Linux OS
      when: ansible_facts['os_family'] == "Debian"
      apt:
        autoremove: yes
    - name: Upgrade all packages on RedHat based Linux OS
      when: ansible_facts['os_family'] == "RedHat"
      dnf:
        name: '*'
        state: latest
    - name: Remove dependancies that are no longer needed on RedHat based Linux OS
      when: ansible_facts['os_family'] == "RedHat"
      dnf:
        autoremove: yes
