---
- name: set file complete
  hosts: all
  become: yes
  tasks:
    - name: check for file
      stat:
        path: "/setup_complete"
      register: check
    - name: create setup_complete
      file:
        path: "/setup_complete"
        state: touch
      when: not check.stat.exists