---
- name: Full site configuration
  hosts: all, !yggdrasil.sport-touring.eu
  become: yes
  pre_tasks:
    - name: Check if the server has been setup completely
      stat:
        path: "/setup_complete"
      register: check
    - name: Install epel repository on RedHat Enterprise Linux or Fedora
      when: not check.stat.exists and (ansible_distribution == "RedHat" or ansible_distribution == "Fedora")
      dnf:
        name:
          - https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    - name: Install epel repository on CentOS
      when: ansible_distribution == "CentOS" and not check.stat.exists
      dnf:
        name:
          - epel-release
        update_cache: yes
        state: latest
    - name: Install the sport-touring.eu base packages on Linux OS
      when: not check.stat.exists
      action: >
        {{ ansible_pkg_mgr }} name=cifs-utils,hostname,qemu-guest-agent,wget,curl,htop,mc,net-tools,nmon,bmon,ncdu,figlet,glances,perl-Getopt-Long,perl-Data-Dumper  update_cache=yes state=latest
    - name: Copy inxi to system
      when: not check.stat.exists
      copy:
        src: /usr/bin/inxi
        dest: /usr/bin/inxi
        owner: root
        group: root
        mode: 0755
    - name: Install Aptitude on Debian based systems
      when: ansible_facts['os_family'] == "Debian" and not check.stat.exists
      apt:
        name: 
          - aptitude
        cache_valid_time: 3600
        state: latest
    - name: Upload and extract profile for throttlemeister
      when: not check.stat.exists
      unarchive:
        src: /home/throttlemeister/profile_proper.tar.gz
        dest: /home/throttlemeister
    - name: Upload and extract profile for root
      when: not check.stat.exists
      unarchive:
        src: /home/throttlemeister/profile_proper.tar.gz
        dest: /root
        owner: root
        group: root
    - name: Set /setup_complete to avoid running these again
      when: not check.stat.exists
      file:
        path: "/setup_complete"
        state: touch
  tasks:
    - name: Let's make sure all packages are up to date on Linux OS
      action: >
        {{ ansible_pkg_mgr }} state:latest update_cache:yes
        {{ ansible_pkg_mgr }} autoremove:yes
    - name: Update inxi to the latest version
      when: ansible_facts['os_family'] != "Debian"
      command: /usr/bin/inxi -U
