# Let's do some stuff we know we need to do for each and every machine
# but we do not want to do this for the Synology!
- name: Talk to all hosts and learn about them
  hosts: localhost
  tasks:
  - name: Classify Linux hosts depending on their distribution
    group_by:
      key: family_{{ ansible_facts['os_family'] }}

# Add the user to sudo
- name: Setup sudo
  hosts: localhost
  tasks:
  - name: Create sudoers file
    lineinfile:
      path: /etc/sudoers.d/throttlemeister
      line: 'throttlemeister ALL=(ALL) NOPASSWD: ALL'
      state: present
      mode: 0440
      create: yes
      validate: 'visudo -cf %s'
  - name: Ensure /etc/sudoers.d is included in sudoers
    lineinfile:
      dest: /etc/sudoers
      line: "#includedir /etc/sudoers.d"
      state: present
      validate: "/usr/sbin/visudo -cf %s"

# Do some OS specific stuff like using distro specific tools
- hosts: family_Suse
  name: Install standard packages 
  become: yes
  gather_facts: False
  tasks:
    - name: Read package list and install applications
      package:
        name: "{{ lookup('file', 'pkg_opensuse.txt').splitlines() }}"
        state: present
    - name: Install Microsoft Visual Studio Code from opi
      command: opi -n vscode
    - name: Install Microsoft Edge Browser from opi
      command: opi -n msedge
