# Let's do some stuff we know we need to do for each and every machine
# but we do not want to do this for the Synology!
- name: Talk to all hosts and learn about them
  hosts: localhost
  tasks:
  - name: Classify Linux hosts depending on their distribution
    group_by:
      key: family_{{ ansible_facts['os_family'] }}

# Do some OS specific stuff like adding the required repositories

# - hosts: family_Suse
#   name: Suse Linux based setup
#   become: yes
#   gather_facts: False
#   tasks:
  #   - name: Install OPI
    #   package:
      #   name: opi
      # state: present
  #   - name: Install VS Code
    #   command: sudo opi -n vscode
  #   - name: Install Microsoft Edge
    #   command: sudo opi -n msedge

# Now finish with the installation of some required packages on any system.
- hosts: localhost
  name: Install packages from file
  become: yes
  tasks:
    - name: Install packages from file
      package:
        name: "{{ lookup('file', 'pkg_opensuse.txt').splitlines() }}"
        state: present
    - name: Install Microsoft Visual Studio Code
      command: opi -n vscode
    - name: Install Microsoft Edge Browser
      command: opi -n msedge
