# Let's do some stuff we know we need to do for each and every machine
# We'll make it somewhat OS agnostic so it can be changed for something
# other than OpenSUSE in the future, if needed.
# So let's see what OS we are using.
- name: Talk to all hosts and learn about them
  hosts: localhost
  tasks:
  - name: Classify Linux hosts depending on their distribution
    group_by:
      key: family_{{ ansible_facts['os_family'] }}

# Do some OS specific stuff like using distro specific tools. We will
# be installing aur standard packages first
- hosts: family_Suse
  name: Install standard packages 
  become: yes
  gather_facts: False
  tasks:
    - name: Read package list and install applications
      package:
        name: "{{ lookup('file', 'pkg_opensuse.txt').splitlines() }}"
        state: present
    - name: Install Microsoft Visual Studio Code from opi
      command: opi -n vscode
    - name: Install Microsoft Edge Browser from opi
      command: opi -n msedge

# Add the user to sudo. This will be the same regardless of what
# we are running. As long as it is Linux.
- name: Setup sudo
  hosts: localhost
  tasks:
  - name: Create sudoers file
    lineinfile:
      path: /etc/sudoers.d/throttlemeister
      line: 'throttlemeister ALL=(ALL) NOPASSWD: ALL'
      state: present
      mode: 0440
      create: yes
      validate: 'visudo -cf %s'
  - name: Ensure /etc/sudoers.d is included in sudoers
    lineinfile:
      dest: /etc/sudoers
      line: "#includedir /etc/sudoers.d"
      state: present
      validate: "/usr/sbin/visudo -cf %s"
